# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish Foresite/Foresite.csproj -o publish
    - name: Deploy
      run: |
        cd publish
        git init
        git remote set origin https://github.com/IVAO-US/Foresite.git
        git switch -c deploy
        git add *
        git commit -m "Deploy"
        git push --force
