# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish Foresite/Foresite.csproj -o publish
    - name: Deploy
      run: |
        git switch -c deploy
        rm -rf Foresite Foresite.sln
        mv publish/* .
        rm -rf publish
        git config user.name "Github Workflow"; git config user.email "us-wm+github@ivao.aero"
        git add -f *; git commit -m "Automated deployment $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --set-upstream origin deploy
